apis:
  - name: api1
    method: GET
    url: https://jsonplaceholder.typicode.com/posts/1
    headers:
      Authorization: Bearer <token>
    payload: ""
    required: false
  - name: api2
    method: GET
    url: https://data.covid19india.org/v4/min/data.min.json
    headers:
      Content-Type: application/json
      Authorization: Bearer <token>
    payload: ""
    required: true
  - name: api3
    method: POST
    url: https://jsonplaceholder.typicode.com/posts
    headers:
      Content-Type: application/json
      Authorization: Bearer <token>
    payload: ""
    required: true
